library(readr)
library(sqldf)

mirnaCluster <- read_csv("~/mirCoopFinal/miRNAClusterandFamily/mirnaCluster.csv")
mirnaFamily <- read_delim("~/mirCoopFinal/miRNAClusterandFamily/miR_Family_Info.txt", 
                          delim = "\t", escape_double = FALSE, 
                          trim_ws = TRUE)

ACC <- read_csv("finalDTDataWBHCorrection/ACC.csv",show_col_types = FALSE)
ACCmirna1Family <- sqldf::sqldf("SELECT ACC.*,miRFamily as miRNA1Family from ACC left join mirnaFamily on lower(ACC.mirna1) = lower(mirnaFamily.MirBaseID)")
ACCmirna2Family <- sqldf::sqldf("SELECT ACCmirna1Family.*,miRFamily as miRNA2Family from ACCmirna1Family left join mirnaFamily on lower(ACCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
ACCmirna1Cluster <- sqldf::sqldf("SELECT ACCmirna2Family.*,clusterString as miRNA1Cluster from ACCmirna2Family left join mirnaCluster on lower(ACCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
ACCmirna2Cluster <- sqldf::sqldf("SELECT ACCmirna1Cluster.*,clusterString as miRNA2Cluster from ACCmirna1Cluster left join mirnaCluster on lower(ACCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(ACCmirna2Cluster,"miRNAClusterandFamily/ACC.csv",row.names = FALSE)


BLCA <- read_csv("finalDTDataWBHCorrection/BLCA.csv",show_col_types = FALSE)
BLCAmirna1Family <- sqldf::sqldf("SELECT BLCA.*,miRFamily as miRNA1Family from BLCA left join mirnaFamily on lower(BLCA.mirna1) = lower(mirnaFamily.MirBaseID)")
BLCAmirna2Family <- sqldf::sqldf("SELECT BLCAmirna1Family.*,miRFamily as miRNA2Family from BLCAmirna1Family left join mirnaFamily on lower(BLCAmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
BLCAmirna1Cluster <- sqldf::sqldf("SELECT BLCAmirna2Family.*,clusterString as miRNA1Cluster from BLCAmirna2Family left join mirnaCluster on lower(BLCAmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
BLCAmirna2Cluster <- sqldf::sqldf("SELECT BLCAmirna1Cluster.*,clusterString as miRNA2Cluster from BLCAmirna1Cluster left join mirnaCluster on lower(BLCAmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(BLCAmirna2Cluster,"miRNAClusterandFamily/BLCA.csv",row.names = FALSE)


BRCA <- read_csv("finalDTDataWBHCorrection/BRCA.csv",show_col_types = FALSE)
BRCAmirna1Family <- sqldf::sqldf("SELECT BRCA.*,miRFamily as miRNA1Family from BRCA left join mirnaFamily on lower(BRCA.mirna1) = lower(mirnaFamily.MirBaseID)")
BRCAmirna2Family <- sqldf::sqldf("SELECT BRCAmirna1Family.*,miRFamily as miRNA2Family from BRCAmirna1Family left join mirnaFamily on lower(BRCAmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
BRCAmirna1Cluster <- sqldf::sqldf("SELECT BRCAmirna2Family.*,clusterString as miRNA1Cluster from BRCAmirna2Family left join mirnaCluster on lower(BRCAmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
BRCAmirna2Cluster <- sqldf::sqldf("SELECT BRCAmirna1Cluster.*,clusterString as miRNA2Cluster from BRCAmirna1Cluster left join mirnaCluster on lower(BRCAmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(BRCAmirna2Cluster,"miRNAClusterandFamily/BRCA.csv",row.names = FALSE)

CESC <- read_csv("finalDTDataWBHCorrection/CESC.csv",show_col_types = FALSE)
CESCmirna1Family <- sqldf::sqldf("SELECT CESC.*,miRFamily as miRNA1Family from CESC left join mirnaFamily on lower(CESC.mirna1) = lower(mirnaFamily.MirBaseID)")
CESCmirna2Family <- sqldf::sqldf("SELECT CESCmirna1Family.*,miRFamily as miRNA2Family from CESCmirna1Family left join mirnaFamily on lower(CESCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
CESCmirna1Cluster <- sqldf::sqldf("SELECT CESCmirna2Family.*,clusterString as miRNA1Cluster from CESCmirna2Family left join mirnaCluster on lower(CESCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
CESCmirna2Cluster <- sqldf::sqldf("SELECT CESCmirna1Cluster.*,clusterString as miRNA2Cluster from CESCmirna1Cluster left join mirnaCluster on lower(CESCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(CESCmirna2Cluster,"miRNAClusterandFamily/CESC.csv",row.names = FALSE)

CHOL <- read_csv("finalDTDataWBHCorrection/CHOL.csv",show_col_types = FALSE)
CHOLmirna1Family <- sqldf::sqldf("SELECT CHOL.*,miRFamily as miRNA1Family from CHOL left join mirnaFamily on lower(CHOL.mirna1) = lower(mirnaFamily.MirBaseID)")
CHOLmirna2Family <- sqldf::sqldf("SELECT CHOLmirna1Family.*,miRFamily as miRNA2Family from CHOLmirna1Family left join mirnaFamily on lower(CHOLmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
CHOLmirna1Cluster <- sqldf::sqldf("SELECT CHOLmirna2Family.*,clusterString as miRNA1Cluster from CHOLmirna2Family left join mirnaCluster on lower(CHOLmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
CHOLmirna2Cluster <- sqldf::sqldf("SELECT CHOLmirna1Cluster.*,clusterString as miRNA2Cluster from CHOLmirna1Cluster left join mirnaCluster on lower(CHOLmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(CHOLmirna2Cluster,"miRNAClusterandFamily/CHOL.csv",row.names = FALSE)

COAD <- read_csv("finalDTDataWBHCorrection/COAD.csv",show_col_types = FALSE)
COADmirna1Family <- sqldf::sqldf("SELECT COAD.*,miRFamily as miRNA1Family from COAD left join mirnaFamily on lower(COAD.mirna1) = lower(mirnaFamily.MirBaseID)")
COADmirna2Family <- sqldf::sqldf("SELECT COADmirna1Family.*,miRFamily as miRNA2Family from COADmirna1Family left join mirnaFamily on lower(COADmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
COADmirna1Cluster <- sqldf::sqldf("SELECT COADmirna2Family.*,clusterString as miRNA1Cluster from COADmirna2Family left join mirnaCluster on lower(COADmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
COADmirna2Cluster <- sqldf::sqldf("SELECT COADmirna1Cluster.*,clusterString as miRNA2Cluster from COADmirna1Cluster left join mirnaCluster on lower(COADmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(COADmirna2Cluster,"miRNAClusterandFamily/COAD.csv",row.names = FALSE)

DLBC <- read_csv("finalDTDataWBHCorrection/DLBC.csv",show_col_types = FALSE)
DLBCmirna1Family <- sqldf::sqldf("SELECT DLBC.*,miRFamily as miRNA1Family from DLBC left join mirnaFamily on lower(DLBC.mirna1) = lower(mirnaFamily.MirBaseID)")
DLBCmirna2Family <- sqldf::sqldf("SELECT DLBCmirna1Family.*,miRFamily as miRNA2Family from DLBCmirna1Family left join mirnaFamily on lower(DLBCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
DLBCmirna1Cluster <- sqldf::sqldf("SELECT DLBCmirna2Family.*,clusterString as miRNA1Cluster from DLBCmirna2Family left join mirnaCluster on lower(DLBCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
DLBCmirna2Cluster <- sqldf::sqldf("SELECT DLBCmirna1Cluster.*,clusterString as miRNA2Cluster from DLBCmirna1Cluster left join mirnaCluster on lower(DLBCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(DLBCmirna2Cluster,"miRNAClusterandFamily/DLBC.csv",row.names = FALSE)

ESCA <- read_csv("finalDTDataWBHCorrection/ESCA.csv",show_col_types = FALSE)
ESCAmirna1Family <- sqldf::sqldf("SELECT ESCA.*,miRFamily as miRNA1Family from ESCA left join mirnaFamily on lower(ESCA.mirna1) = lower(mirnaFamily.MirBaseID)")
ESCAmirna2Family <- sqldf::sqldf("SELECT ESCAmirna1Family.*,miRFamily as miRNA2Family from ESCAmirna1Family left join mirnaFamily on lower(ESCAmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
ESCAmirna1Cluster <- sqldf::sqldf("SELECT ESCAmirna2Family.*,clusterString as miRNA1Cluster from ESCAmirna2Family left join mirnaCluster on lower(ESCAmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
ESCAmirna2Cluster <- sqldf::sqldf("SELECT ESCAmirna1Cluster.*,clusterString as miRNA2Cluster from ESCAmirna1Cluster left join mirnaCluster on lower(ESCAmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(ESCAmirna2Cluster,"miRNAClusterandFamily/ESCA.csv",row.names = FALSE)


HNSC <- read_csv("finalDTDataWBHCorrection/HNSC.csv",show_col_types = FALSE)
HNSCmirna1Family <- sqldf::sqldf("SELECT HNSC.*,miRFamily as miRNA1Family from HNSC left join mirnaFamily on lower(HNSC.mirna1) = lower(mirnaFamily.MirBaseID)")
HNSCmirna2Family <- sqldf::sqldf("SELECT HNSCmirna1Family.*,miRFamily as miRNA2Family from HNSCmirna1Family left join mirnaFamily on lower(HNSCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
HNSCmirna1Cluster <- sqldf::sqldf("SELECT HNSCmirna2Family.*,clusterString as miRNA1Cluster from HNSCmirna2Family left join mirnaCluster on lower(HNSCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
HNSCmirna2Cluster <- sqldf::sqldf("SELECT HNSCmirna1Cluster.*,clusterString as miRNA2Cluster from HNSCmirna1Cluster left join mirnaCluster on lower(HNSCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(HNSCmirna2Cluster,"miRNAClusterandFamily/HNSC.csv",row.names = FALSE)


KICH <- read_csv("finalDTDataWBHCorrection/KICH.csv",show_col_types = FALSE)
KICHmirna1Family <- sqldf::sqldf("SELECT KICH.*,miRFamily as miRNA1Family from KICH left join mirnaFamily on lower(KICH.mirna1) = lower(mirnaFamily.MirBaseID)")
KICHmirna2Family <- sqldf::sqldf("SELECT KICHmirna1Family.*,miRFamily as miRNA2Family from KICHmirna1Family left join mirnaFamily on lower(KICHmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
KICHmirna1Cluster <- sqldf::sqldf("SELECT KICHmirna2Family.*,clusterString as miRNA1Cluster from KICHmirna2Family left join mirnaCluster on lower(KICHmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
KICHmirna2Cluster <- sqldf::sqldf("SELECT KICHmirna1Cluster.*,clusterString as miRNA2Cluster from KICHmirna1Cluster left join mirnaCluster on lower(KICHmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(KICHmirna2Cluster,"miRNAClusterandFamily/KICH.csv",row.names = FALSE)

KIRC <- read_csv("finalDTDataWBHCorrection/KIRC.csv",show_col_types = FALSE)
KIRCmirna1Family <- sqldf::sqldf("SELECT KIRC.*,miRFamily as miRNA1Family from KIRC left join mirnaFamily on lower(KIRC.mirna1) = lower(mirnaFamily.MirBaseID)")
KIRCmirna2Family <- sqldf::sqldf("SELECT KIRCmirna1Family.*,miRFamily as miRNA2Family from KIRCmirna1Family left join mirnaFamily on lower(KIRCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
KIRCmirna1Cluster <- sqldf::sqldf("SELECT KIRCmirna2Family.*,clusterString as miRNA1Cluster from KIRCmirna2Family left join mirnaCluster on lower(KIRCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
KIRCmirna2Cluster <- sqldf::sqldf("SELECT KIRCmirna1Cluster.*,clusterString as miRNA2Cluster from KIRCmirna1Cluster left join mirnaCluster on lower(KIRCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(KIRCmirna2Cluster,"miRNAClusterandFamily/KIRC.csv",row.names = FALSE)

KIRP <- read_csv("finalDTDataWBHCorrection/KIRP.csv",show_col_types = FALSE)
KIRPmirna1Family <- sqldf::sqldf("SELECT KIRP.*,miRFamily as miRNA1Family from KIRP left join mirnaFamily on lower(KIRP.mirna1) = lower(mirnaFamily.MirBaseID)")
KIRPmirna2Family <- sqldf::sqldf("SELECT KIRPmirna1Family.*,miRFamily as miRNA2Family from KIRPmirna1Family left join mirnaFamily on lower(KIRPmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
KIRPmirna1Cluster <- sqldf::sqldf("SELECT KIRPmirna2Family.*,clusterString as miRNA1Cluster from KIRPmirna2Family left join mirnaCluster on lower(KIRPmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
KIRPmirna2Cluster <- sqldf::sqldf("SELECT KIRPmirna1Cluster.*,clusterString as miRNA2Cluster from KIRPmirna1Cluster left join mirnaCluster on lower(KIRPmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(KIRPmirna2Cluster,"miRNAClusterandFamily/KIRP.csv",row.names = FALSE)

LGG <- read_csv("finalDTDataWBHCorrection/LGG.csv",show_col_types = FALSE)
LGGmirna1Family <- sqldf::sqldf("SELECT LGG.*,miRFamily as miRNA1Family from LGG left join mirnaFamily on lower(LGG.mirna1) = lower(mirnaFamily.MirBaseID)")
LGGmirna2Family <- sqldf::sqldf("SELECT LGGmirna1Family.*,miRFamily as miRNA2Family from LGGmirna1Family left join mirnaFamily on lower(LGGmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
LGGmirna1Cluster <- sqldf::sqldf("SELECT LGGmirna2Family.*,clusterString as miRNA1Cluster from LGGmirna2Family left join mirnaCluster on lower(LGGmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
LGGmirna2Cluster <- sqldf::sqldf("SELECT LGGmirna1Cluster.*,clusterString as miRNA2Cluster from LGGmirna1Cluster left join mirnaCluster on lower(LGGmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(LGGmirna2Cluster,"miRNAClusterandFamily/LGG.csv",row.names = FALSE)

LIHC <- read_csv("finalDTDataWBHCorrection/LIHC.csv",show_col_types = FALSE)
LIHCmirna1Family <- sqldf::sqldf("SELECT LIHC.*,miRFamily as miRNA1Family from LIHC left join mirnaFamily on lower(LIHC.mirna1) = lower(mirnaFamily.MirBaseID)")
LIHCmirna2Family <- sqldf::sqldf("SELECT LIHCmirna1Family.*,miRFamily as miRNA2Family from LIHCmirna1Family left join mirnaFamily on lower(LIHCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
LIHCmirna1Cluster <- sqldf::sqldf("SELECT LIHCmirna2Family.*,clusterString as miRNA1Cluster from LIHCmirna2Family left join mirnaCluster on lower(LIHCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
LIHCmirna2Cluster <- sqldf::sqldf("SELECT LIHCmirna1Cluster.*,clusterString as miRNA2Cluster from LIHCmirna1Cluster left join mirnaCluster on lower(LIHCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(LIHCmirna2Cluster,"miRNAClusterandFamily/LIHC.csv",row.names = FALSE)

LUAD <- read_csv("finalDTDataWBHCorrection/LUAD.csv",show_col_types = FALSE)
LUADmirna1Family <- sqldf::sqldf("SELECT LUAD.*,miRFamily as miRNA1Family from LUAD left join mirnaFamily on lower(LUAD.mirna1) = lower(mirnaFamily.MirBaseID)")
LUADmirna2Family <- sqldf::sqldf("SELECT LUADmirna1Family.*,miRFamily as miRNA2Family from LUADmirna1Family left join mirnaFamily on lower(LUADmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
LUADmirna1Cluster <- sqldf::sqldf("SELECT LUADmirna2Family.*,clusterString as miRNA1Cluster from LUADmirna2Family left join mirnaCluster on lower(LUADmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
LUADmirna2Cluster <- sqldf::sqldf("SELECT LUADmirna1Cluster.*,clusterString as miRNA2Cluster from LUADmirna1Cluster left join mirnaCluster on lower(LUADmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(LUADmirna2Cluster,"miRNAClusterandFamily/LUAD.csv",row.names = FALSE)

LUSC <- read_csv("finalDTDataWBHCorrection/LUSC.csv",show_col_types = FALSE)
LUSCmirna1Family <- sqldf::sqldf("SELECT LUSC.*,miRFamily as miRNA1Family from LUSC left join mirnaFamily on lower(LUSC.mirna1) = lower(mirnaFamily.MirBaseID)")
LUSCmirna2Family <- sqldf::sqldf("SELECT LUSCmirna1Family.*,miRFamily as miRNA2Family from LUSCmirna1Family left join mirnaFamily on lower(LUSCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
LUSCmirna1Cluster <- sqldf::sqldf("SELECT LUSCmirna2Family.*,clusterString as miRNA1Cluster from LUSCmirna2Family left join mirnaCluster on lower(LUSCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
LUSCmirna2Cluster <- sqldf::sqldf("SELECT LUSCmirna1Cluster.*,clusterString as miRNA2Cluster from LUSCmirna1Cluster left join mirnaCluster on lower(LUSCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(LUSCmirna2Cluster,"miRNAClusterandFamily/LUSC.csv",row.names = FALSE)

MESO <- read_csv("finalDTDataWBHCorrection/MESO.csv",show_col_types = FALSE)
MESOmirna1Family <- sqldf::sqldf("SELECT MESO.*,miRFamily as miRNA1Family from MESO left join mirnaFamily on lower(MESO.mirna1) = lower(mirnaFamily.MirBaseID)")
MESOmirna2Family <- sqldf::sqldf("SELECT MESOmirna1Family.*,miRFamily as miRNA2Family from MESOmirna1Family left join mirnaFamily on lower(MESOmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
MESOmirna1Cluster <- sqldf::sqldf("SELECT MESOmirna2Family.*,clusterString as miRNA1Cluster from MESOmirna2Family left join mirnaCluster on lower(MESOmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
MESOmirna2Cluster <- sqldf::sqldf("SELECT MESOmirna1Cluster.*,clusterString as miRNA2Cluster from MESOmirna1Cluster left join mirnaCluster on lower(MESOmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(MESOmirna2Cluster,"miRNAClusterandFamily/MESO.csv",row.names = FALSE)

MESO <- read_csv("finalDTDataWBHCorrection/MESO.csv",show_col_types = FALSE)
MESOmirna1Family <- sqldf::sqldf("SELECT MESO.*,miRFamily as miRNA1Family from MESO left join mirnaFamily on lower(MESO.mirna1) = lower(mirnaFamily.MirBaseID)")
MESOmirna2Family <- sqldf::sqldf("SELECT MESOmirna1Family.*,miRFamily as miRNA2Family from MESOmirna1Family left join mirnaFamily on lower(MESOmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
MESOmirna1Cluster <- sqldf::sqldf("SELECT MESOmirna2Family.*,clusterString as miRNA1Cluster from MESOmirna2Family left join mirnaCluster on lower(MESOmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
MESOmirna2Cluster <- sqldf::sqldf("SELECT MESOmirna1Cluster.*,clusterString as miRNA2Cluster from MESOmirna1Cluster left join mirnaCluster on lower(MESOmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(MESOmirna2Cluster,"miRNAClusterandFamily/MESO.csv",row.names = FALSE)

OV <- read_csv("finalDTDataWBHCorrection/OV.csv",show_col_types = FALSE)
OVmirna1Family <- sqldf::sqldf("SELECT OV.*,miRFamily as miRNA1Family from OV left join mirnaFamily on lower(OV.mirna1) = lower(mirnaFamily.MirBaseID)")
OVmirna2Family <- sqldf::sqldf("SELECT OVmirna1Family.*,miRFamily as miRNA2Family from OVmirna1Family left join mirnaFamily on lower(OVmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
OVmirna1Cluster <- sqldf::sqldf("SELECT OVmirna2Family.*,clusterString as miRNA1Cluster from OVmirna2Family left join mirnaCluster on lower(OVmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
OVmirna2Cluster <- sqldf::sqldf("SELECT OVmirna1Cluster.*,clusterString as miRNA2Cluster from OVmirna1Cluster left join mirnaCluster on lower(OVmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(OVmirna2Cluster,"miRNAClusterandFamily/OV.csv",row.names = FALSE)

PAAD <- read_csv("finalDTDataWBHCorrection/PAAD.csv",show_col_types = FALSE)
PAADmirna1Family <- sqldf::sqldf("SELECT PAAD.*,miRFamily as miRNA1Family from PAAD left join mirnaFamily on lower(PAAD.mirna1) = lower(mirnaFamily.MirBaseID)")
PAADmirna2Family <- sqldf::sqldf("SELECT PAADmirna1Family.*,miRFamily as miRNA2Family from PAADmirna1Family left join mirnaFamily on lower(PAADmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
PAADmirna1Cluster <- sqldf::sqldf("SELECT PAADmirna2Family.*,clusterString as miRNA1Cluster from PAADmirna2Family left join mirnaCluster on lower(PAADmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
PAADmirna2Cluster <- sqldf::sqldf("SELECT PAADmirna1Cluster.*,clusterString as miRNA2Cluster from PAADmirna1Cluster left join mirnaCluster on lower(PAADmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(PAADmirna2Cluster,"miRNAClusterandFamily/PAAD.csv",row.names = FALSE)

PCPG <- read_csv("finalDTDataWBHCorrection/PCPG.csv",show_col_types = FALSE)
PCPGmirna1Family <- sqldf::sqldf("SELECT PCPG.*,miRFamily as miRNA1Family from PCPG left join mirnaFamily on lower(PCPG.mirna1) = lower(mirnaFamily.MirBaseID)")
PCPGmirna2Family <- sqldf::sqldf("SELECT PCPGmirna1Family.*,miRFamily as miRNA2Family from PCPGmirna1Family left join mirnaFamily on lower(PCPGmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
PCPGmirna1Cluster <- sqldf::sqldf("SELECT PCPGmirna2Family.*,clusterString as miRNA1Cluster from PCPGmirna2Family left join mirnaCluster on lower(PCPGmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
PCPGmirna2Cluster <- sqldf::sqldf("SELECT PCPGmirna1Cluster.*,clusterString as miRNA2Cluster from PCPGmirna1Cluster left join mirnaCluster on lower(PCPGmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(PCPGmirna2Cluster,"miRNAClusterandFamily/PCPG.csv",row.names = FALSE)

PRAD <- read_csv("finalDTDataWBHCorrection/PRAD.csv",show_col_types = FALSE)
PRADmirna1Family <- sqldf::sqldf("SELECT PRAD.*,miRFamily as miRNA1Family from PRAD left join mirnaFamily on lower(PRAD.mirna1) = lower(mirnaFamily.MirBaseID)")
PRADmirna2Family <- sqldf::sqldf("SELECT PRADmirna1Family.*,miRFamily as miRNA2Family from PRADmirna1Family left join mirnaFamily on lower(PRADmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
PRADmirna1Cluster <- sqldf::sqldf("SELECT PRADmirna2Family.*,clusterString as miRNA1Cluster from PRADmirna2Family left join mirnaCluster on lower(PRADmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
PRADmirna2Cluster <- sqldf::sqldf("SELECT PRADmirna1Cluster.*,clusterString as miRNA2Cluster from PRADmirna1Cluster left join mirnaCluster on lower(PRADmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(PRADmirna2Cluster,"miRNAClusterandFamily/PRAD.csv",row.names = FALSE)

READ <- read_csv("finalDTDataWBHCorrection/READ.csv",show_col_types = FALSE)
READmirna1Family <- sqldf::sqldf("SELECT READ.*,miRFamily as miRNA1Family from READ left join mirnaFamily on lower(READ.mirna1) = lower(mirnaFamily.MirBaseID)")
READmirna2Family <- sqldf::sqldf("SELECT READmirna1Family.*,miRFamily as miRNA2Family from READmirna1Family left join mirnaFamily on lower(READmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
READmirna1Cluster <- sqldf::sqldf("SELECT READmirna2Family.*,clusterString as miRNA1Cluster from READmirna2Family left join mirnaCluster on lower(READmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
READmirna2Cluster <- sqldf::sqldf("SELECT READmirna1Cluster.*,clusterString as miRNA2Cluster from READmirna1Cluster left join mirnaCluster on lower(READmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(READmirna2Cluster,"miRNAClusterandFamily/READ.csv",row.names = FALSE)

SARC <- read_csv("finalDTDataWBHCorrection/SARC.csv",show_col_types = FALSE)
SARCmirna1Family <- sqldf::sqldf("SELECT SARC.*,miRFamily as miRNA1Family from SARC left join mirnaFamily on lower(SARC.mirna1) = lower(mirnaFamily.MirBaseID)")
SARCmirna2Family <- sqldf::sqldf("SELECT SARCmirna1Family.*,miRFamily as miRNA2Family from SARCmirna1Family left join mirnaFamily on lower(SARCmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
SARCmirna1Cluster <- sqldf::sqldf("SELECT SARCmirna2Family.*,clusterString as miRNA1Cluster from SARCmirna2Family left join mirnaCluster on lower(SARCmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
SARCmirna2Cluster <- sqldf::sqldf("SELECT SARCmirna1Cluster.*,clusterString as miRNA2Cluster from SARCmirna1Cluster left join mirnaCluster on lower(SARCmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(SARCmirna2Cluster,"miRNAClusterandFamily/SARC.csv",row.names = FALSE)

SKCM <- read_csv("finalDTDataWBHCorrection/SKCM.csv",show_col_types = FALSE)
SKCMmirna1Family <- sqldf::sqldf("SELECT SKCM.*,miRFamily as miRNA1Family from SKCM left join mirnaFamily on lower(SKCM.mirna1) = lower(mirnaFamily.MirBaseID)")
SKCMmirna2Family <- sqldf::sqldf("SELECT SKCMmirna1Family.*,miRFamily as miRNA2Family from SKCMmirna1Family left join mirnaFamily on lower(SKCMmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
SKCMmirna1Cluster <- sqldf::sqldf("SELECT SKCMmirna2Family.*,clusterString as miRNA1Cluster from SKCMmirna2Family left join mirnaCluster on lower(SKCMmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
SKCMmirna2Cluster <- sqldf::sqldf("SELECT SKCMmirna1Cluster.*,clusterString as miRNA2Cluster from SKCMmirna1Cluster left join mirnaCluster on lower(SKCMmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(SKCMmirna2Cluster,"miRNAClusterandFamily/SKCM.csv",row.names = FALSE)

STAD <- read_csv("finalDTDataWBHCorrection/STAD.csv",show_col_types = FALSE)
STADmirna1Family <- sqldf::sqldf("SELECT STAD.*,miRFamily as miRNA1Family from STAD left join mirnaFamily on lower(STAD.mirna1) = lower(mirnaFamily.MirBaseID)")
STADmirna2Family <- sqldf::sqldf("SELECT STADmirna1Family.*,miRFamily as miRNA2Family from STADmirna1Family left join mirnaFamily on lower(STADmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
STADmirna1Cluster <- sqldf::sqldf("SELECT STADmirna2Family.*,clusterString as miRNA1Cluster from STADmirna2Family left join mirnaCluster on lower(STADmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
STADmirna2Cluster <- sqldf::sqldf("SELECT STADmirna1Cluster.*,clusterString as miRNA2Cluster from STADmirna1Cluster left join mirnaCluster on lower(STADmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(STADmirna2Cluster,"miRNAClusterandFamily/STAD.csv",row.names = FALSE)

TGCT <- read_csv("finalDTDataWBHCorrection/TGCT.csv",show_col_types = FALSE)
TGCTmirna1Family <- sqldf::sqldf("SELECT TGCT.*,miRFamily as miRNA1Family from TGCT left join mirnaFamily on lower(TGCT.mirna1) = lower(mirnaFamily.MirBaseID)")
TGCTmirna2Family <- sqldf::sqldf("SELECT TGCTmirna1Family.*,miRFamily as miRNA2Family from TGCTmirna1Family left join mirnaFamily on lower(TGCTmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
TGCTmirna1Cluster <- sqldf::sqldf("SELECT TGCTmirna2Family.*,clusterString as miRNA1Cluster from TGCTmirna2Family left join mirnaCluster on lower(TGCTmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
TGCTmirna2Cluster <- sqldf::sqldf("SELECT TGCTmirna1Cluster.*,clusterString as miRNA2Cluster from TGCTmirna1Cluster left join mirnaCluster on lower(TGCTmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(TGCTmirna2Cluster,"miRNAClusterandFamily/TGCT.csv",row.names = FALSE)

THCA <- read_csv("finalDTDataWBHCorrection/THCA.csv",show_col_types = FALSE)
THCAmirna1Family <- sqldf::sqldf("SELECT THCA.*,miRFamily as miRNA1Family from THCA left join mirnaFamily on lower(THCA.mirna1) = lower(mirnaFamily.MirBaseID)")
THCAmirna2Family <- sqldf::sqldf("SELECT THCAmirna1Family.*,miRFamily as miRNA2Family from THCAmirna1Family left join mirnaFamily on lower(THCAmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
THCAmirna1Cluster <- sqldf::sqldf("SELECT THCAmirna2Family.*,clusterString as miRNA1Cluster from THCAmirna2Family left join mirnaCluster on lower(THCAmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
THCAmirna2Cluster <- sqldf::sqldf("SELECT THCAmirna1Cluster.*,clusterString as miRNA2Cluster from THCAmirna1Cluster left join mirnaCluster on lower(THCAmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(THCAmirna2Cluster,"miRNAClusterandFamily/THCA.csv",row.names = FALSE)

THYM <- read_csv("finalDTDataWBHCorrection/THYM.csv",show_col_types = FALSE)
THYMmirna1Family <- sqldf::sqldf("SELECT THYM.*,miRFamily as miRNA1Family from THYM left join mirnaFamily on lower(THYM.mirna1) = lower(mirnaFamily.MirBaseID)")
THYMmirna2Family <- sqldf::sqldf("SELECT THYMmirna1Family.*,miRFamily as miRNA2Family from THYMmirna1Family left join mirnaFamily on lower(THYMmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
THYMmirna1Cluster <- sqldf::sqldf("SELECT THYMmirna2Family.*,clusterString as miRNA1Cluster from THYMmirna2Family left join mirnaCluster on lower(THYMmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
THYMmirna2Cluster <- sqldf::sqldf("SELECT THYMmirna1Cluster.*,clusterString as miRNA2Cluster from THYMmirna1Cluster left join mirnaCluster on lower(THYMmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(THYMmirna2Cluster,"miRNAClusterandFamily/THYM.csv",row.names = FALSE)

UCEC <- read_csv("finalDTDataWBHCorrection/UCEC.csv",show_col_types = FALSE)
UCECmirna1Family <- sqldf::sqldf("SELECT UCEC.*,miRFamily as miRNA1Family from UCEC left join mirnaFamily on lower(UCEC.mirna1) = lower(mirnaFamily.MirBaseID)")
UCECmirna2Family <- sqldf::sqldf("SELECT UCECmirna1Family.*,miRFamily as miRNA2Family from UCECmirna1Family left join mirnaFamily on lower(UCECmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
UCECmirna1Cluster <- sqldf::sqldf("SELECT UCECmirna2Family.*,clusterString as miRNA1Cluster from UCECmirna2Family left join mirnaCluster on lower(UCECmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
UCECmirna2Cluster <- sqldf::sqldf("SELECT UCECmirna1Cluster.*,clusterString as miRNA2Cluster from UCECmirna1Cluster left join mirnaCluster on lower(UCECmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(UCECmirna2Cluster,"miRNAClusterandFamily/UCEC.csv")

UCS <- read_csv("finalDTDataWBHCorrection/UCS.csv",show_col_types = FALSE)
UCSmirna1Family <- sqldf::sqldf("SELECT UCS.*,miRFamily as miRNA1Family from UCS left join mirnaFamily on lower(UCS.mirna1) = lower(mirnaFamily.MirBaseID)")
UCSmirna2Family <- sqldf::sqldf("SELECT UCSmirna1Family.*,miRFamily as miRNA2Family from UCSmirna1Family left join mirnaFamily on lower(UCSmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
UCSmirna1Cluster <- sqldf::sqldf("SELECT UCSmirna2Family.*,clusterString as miRNA1Cluster from UCSmirna2Family left join mirnaCluster on lower(UCSmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
UCSmirna2Cluster <- sqldf::sqldf("SELECT UCSmirna1Cluster.*,clusterString as miRNA2Cluster from UCSmirna1Cluster left join mirnaCluster on lower(UCSmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(UCSmirna2Cluster,"miRNAClusterandFamily/UCS.csv",row.names = FALSE)

UVM <- read_csv("finalDTDataWBHCorrection/UVM.csv",show_col_types = FALSE)
UVMmirna1Family <- sqldf::sqldf("SELECT UVM.*,miRFamily as miRNA1Family from UVM left join mirnaFamily on lower(UVM.mirna1) = lower(mirnaFamily.MirBaseID)")
UVMmirna2Family <- sqldf::sqldf("SELECT UVMmirna1Family.*,miRFamily as miRNA2Family from UVMmirna1Family left join mirnaFamily on lower(UVMmirna1Family.mirna2) = lower(mirnaFamily.MirBaseID)")
UVMmirna1Cluster <- sqldf::sqldf("SELECT UVMmirna2Family.*,clusterString as miRNA1Cluster from UVMmirna2Family left join mirnaCluster on lower(UVMmirna2Family.mirna1) = lower(mirnaCluster.mirna)")
UVMmirna2Cluster <- sqldf::sqldf("SELECT UVMmirna1Cluster.*,clusterString as miRNA2Cluster from UVMmirna1Cluster left join mirnaCluster on lower(UVMmirna1Cluster.mirna2) = lower(mirnaCluster.mirna)")
write.csv(UVMmirna2Cluster,"miRNAClusterandFamily/UVM.csv",row.names = FALSE)



